name: hello_world_ffi
version: 0.0.1
description: >-
  A super simple example of calling C code from Dart with FFI

# This example isn't intended for publishing on pub.dev.
pulish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  path: ^1.8.3
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0

