// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtp_iKqTPwa8KDPPvbwRu4XkvD46jfp0M',
    appId: '1:471265855886:web:424b03495e72436244bcdf',
    messagingSenderId: '471265855886',
    projectId: 'fluttertutorialapp-b8fa9',
    authDomain: 'fluttertutorialapp-b8fa9.firebaseapp.com',
    storageBucket: 'fluttertutorialapp-b8fa9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK3KDLNfBP6ns2bVL9G04kM32I5eUncm8',
    appId: '1:471265855886:android:4717c16e968f02ba44bcdf',
    messagingSenderId: '471265855886',
    projectId: 'fluttertutorialapp-b8fa9',
    storageBucket: 'fluttertutorialapp-b8fa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDekbiHEXAarhKqbMV8GBeXGUPbMX6Cl0',
    appId: '1:471265855886:ios:5470a1e0cef0864944bcdf',
    messagingSenderId: '471265855886',
    projectId: 'fluttertutorialapp-b8fa9',
    storageBucket: 'fluttertutorialapp-b8fa9.appspot.com',
    iosBundleId: 'com.example.firebaseServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDekbiHEXAarhKqbMV8GBeXGUPbMX6Cl0',
    appId: '1:471265855886:ios:5470a1e0cef0864944bcdf',
    messagingSenderId: '471265855886',
    projectId: 'fluttertutorialapp-b8fa9',
    storageBucket: 'fluttertutorialapp-b8fa9.appspot.com',
    iosBundleId: 'com.example.firebaseServices',
  );
}
